<?php
/**
 * @var $block \OrviSoft\Reevoo\Block\Js
 */
$_helper = $block->getHelper();
if($_helper->isEnabled()):
?>
<link rel="stylesheet" href="//mark.reevoo.com/assets/embedded_reviews.css" type="text/css" />
<script id="reevoomark-loader" type="text/javascript" charset="utf-8">
	(function() {
		var script = document.createElement('script');
		script.type = 'text/javascript';
		script.src = '//cdn.mark.reevoo.com/assets/reevoo_mark.js';
		var s = document.getElementById('reevoomark-loader');
		s.parentNode.insertBefore(script, s);
	})();
</script>
<script type="text/javascript">
	afterReevooMarkLoaded = [function() {     
		ReevooApi.load('<?php echo $_helper->getPartner() ?>', function(retailer) { 
		var unrendered_badge_count = document.getElementsByClassName('reevoomark').length;      
		retailer.init_badges();     
		unrendered_badge_count += document.getElementsByClassName('reevoo_reputation').length;
		retailer.init_reevoo_reputation_badges();
		});
	}]; 
</script>
<?php endif; ?>